image: golang:1.11

services:
  - postgres:latest

variables:
  POSTGRES_DB: rentals-dev
  POSTGRES_USER: juan
  RENTALS_DB_NAME: $POSTGRES_DB
  RENTALS_DB_USER: $POSTGRES_USER
  RENTALS_DB_HOST: postgres

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - go build ./...

test:
  stage: test
  script:
    - go test ./...

deploy:
  stage: deploy
  script:
    - echo "deploying"